\set ON_ERROR_STOP on
-- This is an isolated local database. These helpers are never installed in production.
create schema test;
create table test.results (label text primary key);
create table test.context (key text primary key, value text not null);
grant usage on schema test to anon, authenticated;
grant insert on test.results to anon, authenticated;
grant select, insert, update on test.context to authenticated;
grant select on test.context to anon;
create function test.ok(condition boolean,label text) returns void language plpgsql as $$ begin
  if condition is distinct from true then raise exception 'FAILED: %',label; end if;
  insert into test.results values(label);
end; $$;
create function test.denied(statement text,expected_state text,label text) returns void language plpgsql as $$
declare received_state text; begin
  begin execute statement; exception when others then get stacked diagnostics received_state = returned_sqlstate; end;
  if received_state is distinct from expected_state then raise exception 'FAILED: %; expected SQLSTATE %, received %',label,expected_state,coalesce(received_state,'success'); end if;
  insert into test.results values(label);
end; $$;
create function test.value(p_key text) returns text language sql stable as $$ select value from test.context where key = p_key; $$;
create function test.lead(p_id text) returns jsonb language sql immutable as $$ select jsonb_build_object(
  'id',p_id,'name','Teste local','company','Empresa teste','email','lead@example.test','phone','','source','Indicação',
  'createdAt','2026-10-07T12:00:00.000Z','callDate','','objection','','closedAt','','lastContactAt','2026-10-07T12:00:00.000Z',
  'notes','','pain','','closerError','','callSummary','','status','Lead novo','attendance','Pendente','urgency','Média',
  'financialCapacity','Não avaliada','decisionMaker',false,'ticket',10000,'closedValue',0,'callScore',null); $$;

insert into auth.users(id,email,email_confirmed_at,raw_user_meta_data)
select ('00000000-0000-0000-0000-' || lpad(n::text,12,'0'))::uuid,'person' || n || '@example.test',
  case when n=8 then null else now() end,case when n=7 then '{"role":"platform_admin"}'::jsonb else '{}' end
from generate_series(1,10) n;
update public.bootstrap_settings set allowed_emails = array['person1@example.test'];
select test.ok((select count(*)=10 from public.profiles),'auth trigger creates profiles');
select test.ok(not exists(select 1 from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relkind='r' and not c.relrowsecurity),'all public tables enable RLS');
select test.ok(not exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace cross join lateral aclexplode(coalesce(p.proacl,acldefault('f',p.proowner))) a where n.nspname in ('public','private') and a.grantee=0 and a.privilege_type='EXECUTE'),'no implicit PUBLIC function execution');
select test.ok(not exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname in ('public','private') and p.prosecdef and not ('search_path=""'=any(p.proconfig))),'security definer functions lock empty search path');
select test.ok(not has_function_privilege('authenticated','private.assert_manage(uuid)','EXECUTE'),'private administrative assertion not externally executable');
select test.ok(not has_function_privilege('authenticated','private.sync_auth_profile()','EXECUTE'),'private auth trigger not externally executable');
select test.ok(not has_sequence_privilege('authenticated','public.audit_logs_id_seq','USAGE'),'clients cannot allocate audit sequence');
select test.ok(has_sequence_privilege('service_role','public.audit_logs_id_seq','USAGE'),'service role owns audit sequence privileges');

set role anon;
select test.denied('select public.bootstrap_owner()','42501','anonymous cannot bootstrap');
select test.denied('select * from public.leads','42501','anonymous cannot read leads');
select test.denied('select * from public.invitations','42501','anonymous cannot enumerate invitations');
select test.ok(public.list_invitation_preview(repeat('0',64)) is null,'anonymous invalid token preview is empty');
reset role;
set role authenticated;
select set_config('request.jwt.claim.sub','00000000-0000-0000-0000-000000000007',false);
select test.denied('select public.bootstrap_owner()','42501','user metadata cannot grant platform administration');
select test.denied('select public.create_workspace(''Unauthorized'')','42501','ordinary account cannot create client');
select test.denied('insert into public.platform_admins(user_id) values(auth.uid())','42501','direct platform privilege escalation denied');
select test.denied('update public.bootstrap_settings set allowed_emails=array[''person7@example.test'']','42501','bootstrap allowlist is service only');
select set_config('request.jwt.claim.sub','00000000-0000-0000-0000-000000000001',false);
select test.ok(public.setup_owner('Operador'),'allowlisted confirmed account bootstraps');
select test.ok(public.bootstrap_owner(),'bootstrap is idempotent for current operator');
insert into test.context values('a',public.create_workspace('Empresa A')::text),('b',public.create_workspace('Empresa B')::text),('race',public.create_workspace('Concorrência')::text);
select test.ok((select plan='individual' and seat_limit=1 and status='trial' from public.subscriptions where workspace_id=test.value('a')::uuid),'new client gets individual one-seat trial');
select test.denied(format('select public.invite_member(%L,''person3@example.test'',''closer'')',test.value('a')),'22023','first invitation must establish tenant administrator');
insert into test.context values('owner_a_token',(public.invite_member(test.value('a')::uuid,'person2@example.test','admin')->>'token'));
insert into test.context values('owner_b_token',(public.invite_member(test.value('b')::uuid,'person6@example.test','admin')->>'token'));
select test.ok(length(test.value('owner_a_token'))=64,'invitation returns unpredictable 256-bit token');
select test.ok((public.list_invitation_preview(test.value('owner_a_token'))->>'workspace_name')='Empresa A','token preview binds to correct workspace');
select test.denied(format('select public.invite_member(%L,''person3@example.test'',''admin'')',test.value('a')),'23514','pending invite reserves sole seat');
-- Reissuing while at capacity must invalidate the first token, without double-counting it.
insert into test.context values('old_token',test.value('owner_a_token'));
update test.context set value=(public.invite_member(test.value('a')::uuid,'person2@example.test','admin')->>'token') where key='owner_a_token';
select test.ok(public.list_invitation_preview(test.value('old_token')) is null,'reissued invite invalidates previous token');
select test.ok((public.list_invitation_preview(test.value('owner_a_token'))->>'email')='person2@example.test','replacement invitation remains usable at seat limit');
select test.denied(format('select public.accept_invitation(%L)',test.value('owner_a_token')),'42501','different verified email cannot consume invitation');
select set_config('request.jwt.claim.sub','00000000-0000-0000-0000-000000000002',false);
select test.ok(public.accept_invitation(test.value('owner_a_token'))=test.value('a')::uuid,'owner accepts invitation');
select test.ok(public.list_invitation_preview(test.value('owner_a_token')) is null,'accepted token cannot be previewed or reused');
select test.denied(format('select public.accept_invitation(%L)',test.value('owner_a_token')),'42501','accepted token is single use');
select test.denied('select public.bootstrap_owner()','42501','second user cannot replace initial operator');
select test.denied(format('select public.admin_update_subscription(%L,''team'',''active'',5)',test.value('a')),'42501','tenant administrator cannot change own billing');
select test.ok((select owner_id=auth.uid() from public.workspaces where id=test.value('a')::uuid),'initial admin becomes workspace owner');
select test.ok((select count(*)=1 from public.workspaces),'tenant A cannot list tenant B');
select test.denied(format('select public.invite_member(%L,''person4@example.test'',''viewer'')',test.value('b')),'42501','tenant administrator cannot invite into another tenant');
select set_config('request.jwt.claim.sub','00000000-0000-0000-0000-000000000006',false);
select test.ok(public.accept_invitation(test.value('owner_b_token'))=test.value('b')::uuid,'second tenant owner accepts');
insert into public.leads(workspace_id,id,owner_id,data) values(test.value('b')::uuid,'b-lead',auth.uid(),test.lead('b-lead'));
select set_config('request.jwt.claim.sub','00000000-0000-0000-0000-000000000001',false);
select public.admin_update_subscription(test.value('a')::uuid,'team','active',5);
select test.denied(format('select public.admin_update_subscription(%L,''arbitrary'',''active'',5)',test.value('a')),'22023','billing accepts only defined plans');
select test.denied(format('select public.admin_update_subscription(%L,''team'',''canceled'',5)',test.value('a')),'22023','billing status has consistent cancelled spelling');
insert into test.context values('closer_token',(public.invite_member(test.value('a')::uuid,'person3@example.test','closer')->>'token')),
 ('viewer_token',(public.invite_member(test.value('a')::uuid,'person4@example.test','viewer')->>'token')),
 ('manager_token',(public.invite_member(test.value('a')::uuid,'person5@example.test','manager')->>'token')),
 ('admin_token',(public.invite_member(test.value('a')::uuid,'person9@example.test','admin')->>'token'));
select test.ok((select count(*)=0 from public.leads),'platform operator has no default lead access');
select test.denied(format('select public.export_workspace(%L)',test.value('a')),'42501','platform operator cannot export customer CRM');
select test.denied(format('select public.delete_workspace(%L,''Empresa A'')',test.value('a')),'42501','platform operator cannot delete customer CRM');
select test.denied(format('select public.update_workspace_privacy(%L,90,''privacy@example.test'')',test.value('a')),'42501','platform operator cannot change customer privacy policy');
select test.denied(format('select public.transfer_workspace_owner(%L,%L)',test.value('a'),'00000000-0000-0000-0000-000000000002'),'42501','platform operator cannot seize customer ownership');
select test.denied(format('select public.import_leads(%L,%L::jsonb,''00000000-0000-0000-0000-000000000003'')',test.value('a'),jsonb_build_array(test.lead('platform-forged'))),'42501','platform operator cannot inject customer leads');
select test.ok(jsonb_array_length(public.list_platform_workspaces())=3,'platform lists client metadata only');
select test.denied(format('select public.admin_update_subscription(%L,''team'',''active'',4)',test.value('a')),'23514','cannot lower seat limit below active plus reserved');
reset role;
select test.ok(not exists(select 1 from public.invitations i join test.context c on c.key like '%token' and i.token_hash=c.value),'raw invitation tokens never stored in invitation table');
select test.ok(not exists(select 1 from public.audit_logs l join test.context c on c.key like '%token' and l.details::text like '%'||c.value||'%'),'audit records never contain invitation tokens');
set role authenticated;
select set_config('request.jwt.claim.sub','00000000-0000-0000-0000-000000000003',false);
select public.accept_invitation(test.value('closer_token'));
insert into public.leads(workspace_id,id,owner_id,data) values(test.value('a')::uuid,'closer-lead',auth.uid(),test.lead('closer-lead'));
select test.ok((select lawful_basis is null from public.leads where id='closer-lead'),'lawful basis stays unspecified until controller records it');
select test.denied(format('insert into public.leads(workspace_id,id,owner_id,data) values(%L,''forged'',%L,%L::jsonb)',test.value('b'),auth.uid(),test.lead('forged')),'42501','closer insert into another tenant denied');
select test.denied(format('insert into public.leads(workspace_id,id,owner_id,data) values(%L,''other-owner'',%L,%L::jsonb)',test.value('a'),'00000000-0000-0000-0000-000000000002',test.lead('other-owner')),'42501','closer cannot assign leads to colleague');
select test.denied(format('update public.leads set owner_id=%L where id=''closer-lead''','00000000-0000-0000-0000-000000000002'),'42501','closer cannot move own lead outside own access');
select test.denied(format('update public.leads set workspace_id=%L where id=''closer-lead''',test.value('b')),'42501','lead workspace cannot be changed');
select test.denied('update public.leads set id=''changed'' where id=''closer-lead''','42501','lead ID cannot be changed');
select test.denied('update public.leads set data=jsonb_set(data,''{ticket}'',''-1'') where id=''closer-lead''','23514','negative ticket rejected by server');
select test.denied('update public.leads set data=jsonb_set(data,''{callScore}'',''11'') where id=''closer-lead''','23514','invalid call rating rejected by server');
select test.denied('update public.leads set lawful_basis=''consent'' where id=''closer-lead''','42501','closer cannot forge legal metadata directly');
select test.denied(format('select public.record_lead_privacy(%L,''closer-lead'',''contract'')',test.value('a')),'42501','closer cannot use privileged privacy RPC');
select test.denied('update public.leads set retention_until=null where id=''closer-lead''','42501','closer cannot bypass retention deadline');
update public.leads set data=jsonb_set(data,'{notes}','"Atualizado"') where id='closer-lead';
select test.ok((select data->>'notes'='Atualizado' from public.leads where id='closer-lead'),'closer updates own lead');
with changed as(delete from public.leads where id='closer-lead' returning id) select test.ok((select count(*)=0 from changed),'closer cannot delete own assigned lead');
select test.denied(format('select public.list_members(%L)',test.value('a')),'42501','closer cannot enumerate membership directory');
select test.denied(format('select public.export_workspace(%L)',test.value('a')),'42501','closer cannot export whole tenant');
select test.denied(format('select public.list_platform_workspaces()'),'42501','closer cannot enumerate platform clients');
select public.record_policy_acceptance('2026-10-07','2026-10-07');
select public.record_policy_acceptance('2026-10-07','2026-10-07');
select test.ok((select count(*)=2 from public.policy_acceptances),'policy versions recorded once each');
select test.denied('update public.profiles set email=''changed@example.test'' where id=auth.uid()','42501','profile update cannot forge verified email');
update public.profiles set display_name='Closer alterado' where id=auth.uid();
select test.ok((select display_name='Closer alterado' from public.profiles where id=auth.uid()),'user updates own display name');
select set_config('request.jwt.claim.sub','00000000-0000-0000-0000-000000000004',false);
select public.accept_invitation(test.value('viewer_token'));
select test.ok((select count(*)=1 from public.leads),'viewer sees own workspace and no other tenant');
select test.denied(format('insert into public.leads(workspace_id,id,owner_id,data) values(%L,''viewer-write'',%L,%L::jsonb)',test.value('a'),'00000000-0000-0000-0000-000000000003',test.lead('viewer-write')),'42501','viewer cannot insert');
with changed as(update public.leads set data=jsonb_set(data,'{notes}','"Invadido"') returning id) select test.ok((select count(*)=0 from changed),'viewer updates no rows');
with changed as(delete from public.leads returning id) select test.ok((select count(*)=0 from changed),'viewer deletes no rows');
with changed as(update public.workspace_settings set revenue_goal=1 returning workspace_id) select test.ok((select count(*)=0 from changed),'viewer cannot edit settings');
select test.denied(format('select public.import_leads(%L,%L::jsonb)',test.value('a'),jsonb_build_array(test.lead('viewer-import'))),'42501','viewer cannot bypass writes through import RPC');
select test.denied(format('select public.export_workspace(%L)',test.value('a')),'42501','viewer cannot export whole tenant');
select test.ok((select count(*)=0 from public.policy_acceptances),'policy acceptance history is private to user');
select set_config('request.jwt.claim.sub','00000000-0000-0000-0000-000000000005',false);
select public.accept_invitation(test.value('manager_token'));
select test.ok(jsonb_array_length(public.list_members(test.value('a')::uuid))=4,'manager can list teammates');
select test.denied(format('select public.update_member(%L,%L,''admin'',true)',test.value('a'),auth.uid()),'42501','manager cannot escalate role');
update public.leads set owner_id='00000000-0000-0000-0000-000000000002' where id='closer-lead';
select test.ok((select owner_id='00000000-0000-0000-0000-000000000002' from public.leads where id='closer-lead'),'manager can distribute lead to editable member');
select test.denied('update public.leads set owner_id=''00000000-0000-0000-0000-000000000004'' where id=''closer-lead''','42501','viewer cannot be assigned editable lead');
update public.workspace_settings set commission_rate=15 where workspace_id=test.value('a')::uuid;
select test.ok((select commission_rate=15 from public.workspace_settings where workspace_id=test.value('a')::uuid),'manager edits workspace goals');
insert into public.leads(workspace_id,id,owner_id,data) values(test.value('a')::uuid,'manager-delete',auth.uid(),test.lead('manager-delete'));
with changed as(delete from public.leads where id='manager-delete' returning id) select test.ok((select count(*)=1 from changed),'manager can delete lead within active tenant');
select set_config('request.jwt.claim.sub','00000000-0000-0000-0000-000000000009',false);
select public.accept_invitation(test.value('admin_token'));
select set_config('request.jwt.claim.sub','00000000-0000-0000-0000-000000000003',false);
select test.ok((select count(*)=0 from public.leads),'closer loses access when lead reassigned');
with changed as(update public.leads set data=jsonb_set(data,'{notes}','"Invadido"') returning id) select test.ok((select count(*)=0 from changed),'closer cannot update another owner lead');
with changed as(delete from public.leads returning id) select test.ok((select count(*)=0 from changed),'closer cannot delete another owner lead');
select test.ok((public.import_leads(test.value('a')::uuid,jsonb_build_array(test.lead('import-one'),test.lead('import-two')))->>'imported')::int=2,'closer imports valid records assigned to self');
select test.ok((public.import_leads(test.value('a')::uuid,jsonb_build_array(test.lead('import-one')))->>'skipped')::int=1,'import never overwrites existing IDs');
select test.denied(format('select public.import_leads(%L,%L::jsonb)',test.value('a'),jsonb_build_array(test.lead('must-rollback'),test.lead('invalid')||'{"ticket":-1}'::jsonb)),'22023','import validates full batch atomically');
select test.ok(not exists(select 1 from public.leads where id='must-rollback'),'invalid batch inserts no partial lead');
select set_config('request.jwt.claim.sub','00000000-0000-0000-0000-000000000002',false);
select test.denied(format('select public.update_member(%L,%L,''closer'',true)',test.value('a'),auth.uid()),'23514','owner cannot be demoted before transfer');
select test.denied(format('select public.update_member(%L,%L,''admin'',false)',test.value('a'),auth.uid()),'23514','owner cannot be deactivated before transfer');
select public.update_member(test.value('a')::uuid,'00000000-0000-0000-0000-000000000003','closer',false);
insert into test.context values('extra_token',(public.invite_member(test.value('a')::uuid,'person10@example.test','closer')->>'token'));
select test.denied(format('select public.update_member(%L,%L,''closer'',true)',test.value('a'),'00000000-0000-0000-0000-000000000003'),'23514','reactivation cannot exceed seats reserved by invites');
select public.revoke_invitation(test.value('a')::uuid,(public.list_invitations(test.value('a')::uuid)->0->>'id')::uuid);
select test.ok(public.list_invitation_preview(test.value('extra_token')) is null,'revoked token is invalid');
select public.update_member(test.value('a')::uuid,'00000000-0000-0000-0000-000000000003','closer',true);
select test.ok(jsonb_array_length(public.list_members(test.value('a')::uuid))=5,'reactivation succeeds after reservation released');
select public.update_workspace_privacy(test.value('a')::uuid,90,'privacy@example.test');
select test.ok((select retention_days=90 and privacy_contact_email='privacy@example.test' from public.workspaces where id=test.value('a')::uuid),'privacy policy RPC saves validated metadata');
select test.denied(format('select public.update_workspace_privacy(%L,0,''invalid'')',test.value('a')),'22023','invalid retention policy rejected');
select public.transfer_workspace_owner(test.value('a')::uuid,'00000000-0000-0000-0000-000000000009');
select test.ok((select owner_id='00000000-0000-0000-0000-000000000009' from public.workspaces where id=test.value('a')::uuid),'ownership transfers to active admin');
select test.denied(format('select public.transfer_workspace_owner(%L,%L)',test.value('a'),'00000000-0000-0000-0000-000000000002'),'42501','former owner cannot transfer ownership again');
select set_config('request.jwt.claim.sub','00000000-0000-0000-0000-000000000009',false);
select public.transfer_workspace_owner(test.value('a')::uuid,'00000000-0000-0000-0000-000000000002');
select set_config('request.jwt.claim.sub','00000000-0000-0000-0000-000000000002',false);
select test.denied(format('select public.record_lead_privacy(%L,''import-one'',''consent'')',test.value('a')),'22023','consent basis requires evidence timestamp');
select test.denied(format('select public.record_lead_privacy(%L,''import-one'',''invented'')',test.value('a')),'22023','privacy RPC rejects unknown basis');
select public.record_lead_privacy(test.value('a')::uuid,'import-one','consent',now()-interval '2 days',now()-interval '1 day');
select test.ok((select lawful_basis='consent' and consent_at is not null from public.leads where id='import-one'),'tenant administrator records explicit privacy basis and evidence');
select test.ok(public.purge_expired_leads(test.value('a')::uuid)=1,'privacy purge deletes only records whose retention elapsed');
select test.ok((select count(*)=2 from public.leads),'privacy purge preserves retained tenant records');
select test.ok(jsonb_array_length(public.export_workspace(test.value('a')::uuid)->'leads')=2,'tenant admin exports complete CRM');
select test.denied(format('select public.delete_workspace(%L,''wrong name'')',test.value('a')),'22023','hard delete requires exact confirmation');
select set_config('request.jwt.claim.sub','00000000-0000-0000-0000-000000000001',false);
select public.admin_update_subscription(test.value('a')::uuid,'team','active',5,now()-interval '1 hour');
select test.ok((select count(*)=0 from public.leads),'expired active subscription blocks platform lead reads');
select set_config('request.jwt.claim.sub','00000000-0000-0000-0000-000000000002',false);
select test.ok((select count(*)=0 from public.leads),'expired active subscription blocks customer CRM reads');
select test.denied(format('insert into public.leads(workspace_id,id,owner_id,data) values(%L,''expired-write'',%L,%L::jsonb)',test.value('a'),auth.uid(),test.lead('expired-write')),'42501','expired active subscription blocks new lead writes');
select test.ok(jsonb_array_length(public.export_workspace(test.value('a')::uuid)->'leads')=2,'expired account retains tenant admin portability');
select test.ok((select count(*)=1 from public.workspaces),'expired account can read billing and workspace metadata');
select set_config('request.jwt.claim.sub','00000000-0000-0000-0000-000000000001',false);
select public.admin_update_subscription(test.value('a')::uuid,'team','trial',5,null,now()-interval '1 hour');
select set_config('request.jwt.claim.sub','00000000-0000-0000-0000-000000000002',false);
select test.denied(format('select public.import_leads(%L,%L::jsonb)',test.value('a'),jsonb_build_array(test.lead('expired-trial'))),'42501','expired trial blocks imports');
select test.denied(format('select public.invite_member(%L,''person10@example.test'',''closer'')',test.value('a')),'42501','expired trial blocks issuing invitations');
select set_config('request.jwt.claim.sub','00000000-0000-0000-0000-000000000001',false);
select public.admin_update_subscription(test.value('a')::uuid,'team','cancelled',5);
select set_config('request.jwt.claim.sub','00000000-0000-0000-0000-000000000002',false);
select test.ok((select count(*)=0 from public.leads),'cancelled subscription blocks tenant lead reads');
select set_config('request.jwt.claim.sub','00000000-0000-0000-0000-000000000001',false);
select public.admin_update_subscription(test.value('a')::uuid,'team','active',5,now()+interval '30 days');
select set_config('request.jwt.claim.sub','00000000-0000-0000-0000-000000000002',false);
select public.update_member(test.value('a')::uuid,'00000000-0000-0000-0000-000000000003','closer',false);
select set_config('request.jwt.claim.sub','00000000-0000-0000-0000-000000000003',false);
select test.ok((select count(*)=0 from public.leads),'deactivated account loses previously owned CRM rows');
with changed as(update public.leads set data=jsonb_set(data,'{notes}','"Invadido"') returning id) select test.ok((select count(*)=0 from changed),'deactivated account cannot mutate existing owned leads');
select test.ok((select count(*)=0 from public.workspaces),'deactivated account loses workspace metadata');
select test.denied(format('select public.export_workspace(%L)',test.value('a')),'42501','deactivated account cannot export');
select set_config('request.jwt.claim.sub','00000000-0000-0000-0000-000000000002',false);
select public.delete_workspace(test.value('a')::uuid,'Empresa A');
reset role;
select test.ok(not exists(select 1 from public.leads where workspace_id=test.value('a')::uuid),'workspace hard deletion cascades leads');
select test.ok(not exists(select 1 from public.memberships where workspace_id=test.value('a')::uuid),'workspace hard deletion cascades memberships');
select test.ok(not exists(select 1 from public.invitations where workspace_id=test.value('a')::uuid),'workspace hard deletion cascades invitation hashes');
select test.ok(not exists(select 1 from public.subscriptions where workspace_id=test.value('a')::uuid),'workspace hard deletion cascades billing');
select test.ok((select count(*)=1 from public.leads where workspace_id=test.value('b')::uuid),'hard deletion preserves other tenant CRM');
select test.ok(exists(select 1 from public.audit_logs where action='workspace.deleted' and workspace_id is null),'deletion retains minimal administrative audit');
-- Extra fixtures for independent parallel transactions in test-database.sh.
set role authenticated;
select set_config('request.jwt.claim.sub','00000000-0000-0000-0000-000000000001',false);
insert into test.context values('expiry',public.create_workspace('Expiry test')::text);
insert into test.context values('unconfirmed_token',(public.invite_member(test.value('expiry')::uuid,'person8@example.test','admin')->>'token'));
select set_config('request.jwt.claim.sub','00000000-0000-0000-0000-000000000008',false);
select test.denied(format('select public.accept_invitation(%L)',test.value('unconfirmed_token')),'42501','unconfirmed email cannot accept valid invitation');
reset role;
update public.invitations set expires_at=now()-interval '1 hour',created_at=now()-interval '8 days' where workspace_id=test.value('expiry')::uuid;
set role anon;
select test.ok(public.list_invitation_preview(test.value('unconfirmed_token')) is null,'expired invitation is hidden from token preview');
reset role;
set role authenticated;
select set_config('request.jwt.claim.sub','00000000-0000-0000-0000-000000000008',false);
select test.denied(format('select public.accept_invitation(%L)',test.value('unconfirmed_token')),'42501','expired invitation cannot be accepted');
reset role;
select 'SQL assertions passed: ' || count(*) from test.results;
-- Set up an invitation for simultaneous callbacks, plus administrators for concurrent revocation.
set role authenticated;
select set_config('request.jwt.claim.sub','00000000-0000-0000-0000-000000000001',false);
insert into test.context values('accept_race',public.create_workspace('Acceptance race')::text);
insert into test.context values('accept_race_token',public.invite_member(test.value('accept_race')::uuid,'person6@example.test','admin')->>'token');
insert into test.context values('admin_race',public.create_workspace('Administration race')::text);
select public.admin_update_subscription(test.value('admin_race')::uuid,'team','active',3);
insert into test.context values('admin_race_owner_token',public.invite_member(test.value('admin_race')::uuid,'person6@example.test','admin')->>'token');
select set_config('request.jwt.claim.sub','00000000-0000-0000-0000-000000000006',false);
select public.accept_invitation(test.value('admin_race_owner_token'));
insert into test.context values('admin_race_a_token',public.invite_member(test.value('admin_race')::uuid,'person9@example.test','admin')->>'token');
insert into test.context values('admin_race_b_token',public.invite_member(test.value('admin_race')::uuid,'person10@example.test','admin')->>'token');
select set_config('request.jwt.claim.sub','00000000-0000-0000-0000-000000000009',false);
select public.accept_invitation(test.value('admin_race_a_token'));
select set_config('request.jwt.claim.sub','00000000-0000-0000-0000-000000000010',false);
select public.accept_invitation(test.value('admin_race_b_token'));
reset role;
