\set ON_ERROR_STOP on
-- Run after rls.sql in the disposable local test database, never against production.
select test.ok(has_function_privilege('authenticated','public.create_own_workspace(text,text,boolean)','EXECUTE'),'self-service is available to authenticated customers');
select test.ok(has_function_privilege('service_role','public.create_own_workspace(text,text,boolean)','EXECUTE'),'service role may execute self-service with a customer context');
select test.ok(not has_function_privilege('anon','public.create_own_workspace(text,text,boolean)','EXECUTE'),'anonymous role has no self-service execution grant');
select test.ok((select relrowsecurity from pg_class where oid='private.self_service_registrations'::regclass),'self-service ledger has RLS enabled');
select test.ok(not has_table_privilege('authenticated','private.self_service_registrations','SELECT'),'customers cannot read trial allowance ledger');
select test.ok(not has_table_privilege('authenticated','private.self_service_registrations','INSERT'),'customers cannot insert trial allowance ledger');
select test.ok(not has_table_privilege('authenticated','private.self_service_registrations','UPDATE'),'customers cannot edit trial allowance ledger');
select test.ok(not has_table_privilege('authenticated','private.self_service_registrations','DELETE'),'customers cannot reset trial allowance ledger');
select test.ok(has_table_privilege('service_role','private.self_service_registrations','SELECT,INSERT,UPDATE,DELETE'),'service role can maintain trial allowance ledger');
select test.ok(not exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace cross join lateral aclexplode(coalesce(p.proacl,acldefault('f',p.proowner))) a where n.nspname in ('public','private') and a.grantee=0 and a.privilege_type='EXECUTE'),'self-service adds no implicit PUBLIC function execution');
select test.ok((select 'search_path=""'=any(proconfig) from pg_proc where oid='public.create_own_workspace(text,text,boolean)'::regprocedure),'self-service locks empty search path');

set role anon;
select test.denied('select public.create_own_workspace(''Empresa anônima'',''Visitante'',true)','42501','anonymous cannot create self-service workspace');
reset role;
set role authenticated;
select set_config('request.jwt.claim.sub','',false);
select test.denied('select public.create_own_workspace(''Sem sessão'',''Visitante'',true)','42501','missing authenticated identity cannot create workspace');
select set_config('request.jwt.claim.sub','00000000-0000-0000-0000-000000000099',false);
select test.denied('select public.create_own_workspace(''Identidade inexistente'',''Visitante'',true)','42501','unknown identity cannot create workspace');
select set_config('request.jwt.claim.sub','00000000-0000-0000-0000-000000000008',false);
select test.denied('select public.create_own_workspace(''Sem confirmação'',''Visitante'',true)','42501','unconfirmed email cannot create own workspace');
select set_config('request.jwt.claim.sub','00000000-0000-0000-0000-000000000007',false);
select test.denied('select public.create_own_workspace(''Empresa cliente'',''Cliente'')','22023','self-service requires explicit policy acceptance');
select test.denied('select public.create_own_workspace(''Empresa cliente'',''Cliente'',false)','22023','false policy acceptance is rejected');
select test.denied('select public.create_own_workspace(''Empresa cliente'',''Cliente'',null)','22023','null policy acceptance is rejected');
select test.denied(format('select public.create_own_workspace(%L,''Cliente'',true)', E'\t\n'),'22023','whitespace-only control name is rejected');
select test.denied(format('select public.create_own_workspace(''Empresa'',%L,true)', E'Cliente\nTeste'),'22023','control characters in public display name are rejected');
select test.denied('select public.create_own_workspace(null,''Cliente'',true)','22023','null workspace name is rejected');
select test.denied('select public.create_own_workspace(''   '',''Cliente'',true)','22023','blank workspace name is rejected');
select test.denied('select public.create_own_workspace(repeat(''a'',121),''Cliente'',true)','22023','overlong workspace name is rejected');
select test.denied('select public.create_own_workspace(''Empresa cliente'',null,true)','22023','null display name is rejected');
select test.denied('select public.create_own_workspace(''Empresa cliente'',''   '',true)','22023','blank display name is rejected');
select test.denied('select public.create_own_workspace(''Empresa cliente'',repeat(''a'',121),true)','22023','overlong display name is rejected');
reset role;
select test.ok(not exists(select 1 from private.self_service_registrations where user_id in ('00000000-0000-0000-0000-000000000007','00000000-0000-0000-0000-000000000008')),'rejected registrations consume no trial allowance');
select test.ok(not exists(select 1 from public.workspaces where owner_id in ('00000000-0000-0000-0000-000000000007','00000000-0000-0000-0000-000000000008')),'rejected registrations create no partial workspace');

set role authenticated;
select set_config('request.jwt.claim.sub','00000000-0000-0000-0000-000000000007',false);
insert into test.context values('self',public.create_own_workspace('  Empresa própria  ','  Cliente verificado  ',true)::text);
select test.ok((select owner_id=auth.uid() and name='Empresa própria' from public.workspaces where id=test.value('self')::uuid),'confirmed customer creates and owns named workspace');
select test.ok((select role='admin' and is_active from public.memberships where workspace_id=test.value('self')::uuid and user_id=auth.uid()),'creator gets active tenant administrator membership');
select test.ok((select name='Empresa própria' and commission_rate=10 and revenue_goal=200000 from public.workspace_settings where workspace_id=test.value('self')::uuid),'self-service creates default settings with trimmed workspace name');
select test.ok((select plan='individual' and seat_limit=1 and status='trial' and billing_method='manual' and trial_ends_at between created_at+interval '14 days'-interval '1 second' and created_at+interval '14 days'+interval '1 second' from public.subscriptions where workspace_id=test.value('self')::uuid),'self-service starts individual one-seat fourteen-day trial');
select test.ok((select display_name='Cliente verificado' from public.profiles where id=auth.uid()),'self-service saves trimmed own display name');
select test.ok((select count(*)=2 from public.policy_acceptances where user_id=auth.uid() and document_version='2026-10-06'),'self-service records both current policy acceptances');
select test.ok((select count(*)=0 from public.platform_admins),'self-service metadata does not grant platform administration');
select test.denied('select public.create_workspace(''Cliente alheio'')','42501','self-service administrator cannot create clients as platform operator');
select test.denied(format('select public.admin_update_subscription(%L,''team'',''active'',5)',test.value('self')),'42501','self-service administrator cannot upgrade own billing');
select test.denied('select public.list_platform_workspaces()','42501','self-service administrator cannot enumerate platform clients');
select test.denied('select * from private.self_service_registrations','42501','self-service customer cannot read even own allowance row');
select test.denied('delete from private.self_service_registrations where user_id=auth.uid()','42501','self-service customer cannot delete own allowance row');
select test.ok(public.create_own_workspace('Nome diferente','Nome de perfil diferente',true)=test.value('self')::uuid,'self-service retry returns original workspace');
select test.ok((select name='Empresa própria' from public.workspaces where id=test.value('self')::uuid),'self-service retry never renames original workspace');
select test.ok((select display_name='Cliente verificado' from public.profiles where id=auth.uid()),'self-service retry never overwrites profile name');
insert into public.leads(workspace_id,id,owner_id,data) values(test.value('self')::uuid,'self-private-lead',auth.uid(),test.lead('self-private-lead'));
select test.ok((select count(*)=1 from public.leads),'self-service administrator reads own newly created CRM');
reset role;
select test.ok((select count(*)=1 from private.self_service_registrations where user_id='00000000-0000-0000-0000-000000000007' and workspace_id=test.value('self')::uuid),'idempotent creation consumes exactly one trial allowance');
select test.ok((select count(*)=1 from public.audit_logs where workspace_id=test.value('self')::uuid and action='workspace.self_service_created'),'idempotent creation emits a single creation audit');
select test.ok((select details='{}'::jsonb from public.audit_logs where workspace_id=test.value('self')::uuid and action='workspace.self_service_created'),'self-service creation audit contains no names or contact details');
update public.subscriptions set plan='team',status='active',seat_limit=4,current_period_end=now()+interval '30 days',trial_ends_at=now()-interval '1 day' where workspace_id=test.value('self')::uuid;
insert into test.context values('self_original_trial',(select trial_ends_at::text from public.subscriptions where workspace_id=test.value('self')::uuid));
set role authenticated;
select set_config('request.jwt.claim.sub','00000000-0000-0000-0000-000000000007',false);
select test.ok(public.create_own_workspace('Nova empresa tentativa','Outro nome',true)=test.value('self')::uuid,'retry preserves workspace after billing changes');
select test.ok((select plan='team' and status='active' and seat_limit=4 and trial_ends_at=test.value('self_original_trial')::timestamptz from public.subscriptions where workspace_id=test.value('self')::uuid),'retry never resets upgraded plan seats status or trial');
select set_config('request.jwt.claim.sub','00000000-0000-0000-0000-000000000006',false);
select test.ok(not exists(select 1 from public.workspaces where id=test.value('self')::uuid),'other tenant cannot view self-service workspace');
select test.ok(not exists(select 1 from public.leads where id='self-private-lead'),'other tenant cannot view self-service leads');
insert into test.context values('self_other_memberships',(select count(*)::text from public.memberships where user_id=auth.uid()));
insert into test.context values('self_with_memberships',public.create_own_workspace('Minha empresa independente','Cliente de várias equipes',true)::text);
select test.ok((select count(*)=test.value('self_other_memberships')::integer+1 from public.memberships where user_id=auth.uid()),'existing member creates own workspace without losing other memberships');
select test.ok((select owner_id=auth.uid() from public.workspaces where id=test.value('self_with_memberships')::uuid),'existing team member owns only newly created workspace');
select test.ok((select role='admin' and is_active from public.memberships where user_id=auth.uid() and workspace_id=test.value('b')::uuid),'self-service does not change existing tenant membership');
select test.ok((select name='Empresa B' and owner_id=auth.uid() from public.workspaces where id=test.value('b')::uuid),'self-service preserves existing customer workspace metadata');
select test.ok((select count(*)=0 from public.platform_admins),'existing member remains ordinary tenant user after self-service');
select set_config('request.jwt.claim.sub','00000000-0000-0000-0000-000000000007',false);
select public.delete_workspace(test.value('self')::uuid,'Empresa própria');
select test.denied('select public.create_own_workspace(''Novo teste'',''Cliente verificado'',true)','23514','deleted self-service workspace cannot be recreated to reset trial');
reset role;
select test.ok((select workspace_id is null from private.self_service_registrations where user_id='00000000-0000-0000-0000-000000000007'),'workspace deletion preserves trial ledger tombstone');
select test.ok(not exists(select 1 from public.workspaces where id=test.value('self')::uuid),'self-service workspace hard delete removes workspace');
select test.ok(not exists(select 1 from public.leads where workspace_id=test.value('self')::uuid),'self-service workspace hard delete removes private leads');
select test.ok((select count(*)=2 from public.policy_acceptances where user_id='00000000-0000-0000-0000-000000000007' and document_version='2026-10-06'),'workspace deletion preserves user policy acceptance evidence');
select test.ok(exists(select 1 from public.audit_logs where action='workspace.self_service_created' and actor_id='00000000-0000-0000-0000-000000000007' and workspace_id is null),'workspace deletion preserves minimal self-service audit');
-- Deleting the actual Auth identity also deletes its private allowance ledger.
insert into auth.users(id,email,email_confirmed_at) values('00000000-0000-0000-0000-000000000012','identity-deletion@example.test',now());
set role authenticated;
select set_config('request.jwt.claim.sub','00000000-0000-0000-0000-000000000012',false);
insert into test.context values('self_identity_delete',public.create_own_workspace('Empresa identidade excluída','Titular',true)::text);
select public.delete_workspace(test.value('self_identity_delete')::uuid,'Empresa identidade excluída');
reset role;
delete from auth.users where id='00000000-0000-0000-0000-000000000012';
select test.ok(not exists(select 1 from private.self_service_registrations where user_id='00000000-0000-0000-0000-000000000012'),'identity deletion removes private trial allowance ledger');
select test.ok(not exists(select 1 from public.policy_acceptances where user_id='00000000-0000-0000-0000-000000000012'),'identity deletion removes own policy evidence');
-- Separate verified fixture reserved for real simultaneous create requests in the harness.
insert into auth.users(id,email,email_confirmed_at) values('00000000-0000-0000-0000-000000000011','self-race@example.test',now());
insert into test.context values('self_race','00000000-0000-0000-0000-000000000011');
select 'Self-service assertions passed: ' || count(*) from test.results;
