import { expect, test, type Page, type TestInfo } from '@playwright/test'
import { mkdir } from 'node:fs/promises'
import { resolve } from 'node:path'
import { createFeatureState, memberIds, mountFeatures, navigateFeatures, openCall, workspaceA, workspaceB } from './fixtures/features'

const revenue = (page: Page) => page.locator('.stat-card').filter({ has: page.getByText('Faturamento', { exact: true }) }).locator('.stat-value')
const stageWrites = (state: ReturnType<typeof createFeatureState>) => state.requests.filter(request => request.path.endsWith('/save_pipeline_stages'))
const leadWrites = (state: ReturnType<typeof createFeatureState>) => state.requests.filter(request => request.path === '/rest/v1/leads' && request.method === 'PATCH')
const reviewWrites = (state: ReturnType<typeof createFeatureState>) => state.requests.filter(request => request.path.endsWith('/review_call'))
function clean(state: ReturnType<typeof createFeatureState>) { expect(state.unexpected).toEqual([]); expect(state.errors).toEqual([]) }
async function openConfiguration(page: Page) {
  await navigateFeatures(page, 'Pipeline')
  await page.getByRole('button', { name: 'Configurar pipeline', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: 'Configurar pipeline', exact: true })
  await expect(dialog).toBeVisible(); return dialog
}
async function screenshot(page: Page, info: TestInfo, suffix: string) {
  await mkdir(resolve('.playwright/features-shots'), { recursive: true })
  const path = resolve('.playwright/features-shots', `${info.title.replace(/[^a-z0-9]+/gi, '-').toLowerCase()}-${suffix}.png`)
  await page.screenshot({ path, fullPage: true, animations: 'disabled' }); await info.attach(suffix, { path, contentType: 'image/png' })
}
async function noOverflow(page: Page) {
  expect(await page.evaluate(() => document.documentElement.scrollWidth), 'The board/table may scroll internally; the document must fit').toBeLessThanOrEqual(await page.evaluate(() => innerWidth) + 1)
}

test('admin adds a stage and renames WON without changing stage identity, mapping or revenue', async ({ page }) => {
  const state = await mountFeatures(page), original = state.stages[workspaceA].map(row => ({ ...row }))
  await expect(revenue(page)).toHaveText(/R\$\s*18\.000/)
  const dialog = await openConfiguration(page)
  await expect(dialog.getByRole('button', { name: 'Excluir etapa Compareceu', exact: true })).toBeDisabled()
  await expect(dialog.getByLabel('Tipo da etapa').nth(3)).toBeDisabled()
  await dialog.getByLabel('Nome da etapa').nth(5).fill('Contrato assinado')
  await dialog.getByRole('button', { name: 'Nova etapa', exact: true }).click()
  await dialog.getByLabel('Nome da etapa').last().fill('Diagnóstico aprofundado')
  await dialog.getByLabel('Cor da etapa').last().fill('#405dc7')
  await dialog.getByRole('button', { name: 'Salvar pipeline', exact: true }).click()
  await expect(dialog).not.toBeVisible()
  const won = state.stages[workspaceA].find(row => row.type === 'WON')!
  expect(won).toMatchObject({ id: original[5].id, name: 'Contrato assinado', type: 'WON' })
  expect(state.leads.find(row => row.data.name === 'Carla Torres')?.stage_id).toBe(original[5].id)
  await expect(page.getByLabel('Etapa de Carla Torres').locator('option:checked')).toHaveText('Contrato assinado')
  await expect(page.getByRole('heading', { name: 'Diagnóstico aprofundado', exact: true })).toBeVisible()
  await navigateFeatures(page, 'Dashboard'); await expect(revenue(page)).toHaveText(/R\$\s*18\.000/)
  await page.reload(); await expect(revenue(page)).toHaveText(/R\$\s*18\.000/)
  expect(stageWrites(state)).toHaveLength(1)
  expect(stageWrites(state)[0].body?.p_workspace_id).toBe(workspaceA)
  expect(leadWrites(state)).toHaveLength(0); clean(state)
})

test('empty NORMAL stages can be deactivated or safely deleted while WON and LOST remain available', async ({ page }) => {
  const state = await mountFeatures(page), before = structuredClone(state.leads)
  const dialog = await openConfiguration(page)
  await expect(dialog.getByRole('button', { name: 'Excluir etapa Perdido', exact: true })).toBeDisabled()
  await dialog.getByLabel('Etapa ativa').nth(1).uncheck()
  await dialog.getByRole('button', { name: 'Excluir etapa Lead novo', exact: true }).click()
  await dialog.getByRole('button', { name: 'Salvar pipeline', exact: true }).click()
  await expect(dialog).not.toBeVisible()
  expect(state.stages[workspaceA].some(stage => stage.name === 'Lead novo')).toBe(false)
  expect(state.stages[workspaceA].find(stage => stage.name === 'Qualificado')?.active).toBe(false)
  expect(state.stages[workspaceA].filter(stage => stage.active && stage.type === 'WON')).toHaveLength(1)
  expect(state.stages[workspaceA].filter(stage => stage.active && stage.type === 'LOST')).toHaveLength(1)
  expect(state.leads).toEqual(before); expect(leadWrites(state)).toHaveLength(0)
  await expect(page.getByLabel('Etapa de Ana Ribeiro').locator('option', { hasText: 'Qualificado' })).toHaveAttribute('disabled', '')
  await expect(page.locator('.kanban-column-header h2').filter({ hasText: /^Qualificado$/ })).toHaveCount(0); clean(state)
})

test('manager can reorder stages by drag and keyboard-friendly buttons while preserving lead links', async ({ page }) => {
  const state = await mountFeatures(page, 'manager'), oldIds = state.leads.map(row => row.stage_id)
  const dialog = await openConfiguration(page)
  const rows = dialog.locator('.pf-config-stage')
  // Adjacent visible rows avoid scrolling the source out of view before the drag starts.
  await rows.nth(1).dragTo(rows.nth(0), { sourcePosition: { x: 10, y: 10 }, targetPosition: { x: 10, y: 10 } })
  await expect(dialog.getByLabel('Nome da etapa').first()).toHaveValue('Qualificado')
  await dialog.getByRole('button', { name: 'Mover etapa Lead novo para cima', exact: true }).click()
  await expect(dialog.getByLabel('Nome da etapa').first()).toHaveValue('Lead novo')
  await dialog.getByRole('button', { name: 'Mover etapa Qualificado para cima', exact: true }).click()
  await expect(dialog.getByLabel('Nome da etapa').first()).toHaveValue('Qualificado')
  await dialog.getByRole('button', { name: 'Salvar pipeline', exact: true }).click()
  await expect(dialog).not.toBeVisible()
  expect(state.stages[workspaceA][0].name).toBe('Qualificado')
  expect(state.leads.map(row => row.stage_id)).toEqual(oldIds)
  await page.reload(); await navigateFeatures(page, 'Pipeline')
  await expect(page.locator('.kanban-column-header h2').first()).toHaveText('Qualificado')
  expect(stageWrites(state)).toHaveLength(1); clean(state)
})

test('closer sees company stages and can move owned leads but cannot configure the pipeline', async ({ page }) => {
  const state = await mountFeatures(page, 'closer')
  await navigateFeatures(page, 'Pipeline')
  await expect(page.getByRole('button', { name: 'Configurar pipeline', exact: true })).toHaveCount(0)
  await page.getByLabel('Etapa de Ana Ribeiro').selectOption({ label: 'Follow-up' })
  await expect(page.getByLabel('Etapa de Ana Ribeiro').locator('option:checked')).toHaveText('Follow-up')
  expect(state.leads.find(row => row.data.name === 'Ana Ribeiro')?.stage_id).toBe(state.stages[workspaceA][4].id)
  expect(stageWrites(state)).toHaveLength(0); expect(leadWrites(state)).toHaveLength(1); clean(state)
})

test('WON asks for the actual closed amount; cancellation and zero never write or add revenue', async ({ page }) => {
  const state = await mountFeatures(page)
  await navigateFeatures(page, 'Pipeline')
  await page.getByLabel('Etapa de Ana Ribeiro').selectOption({ label: 'Fechado' })
  const dialog = page.getByRole('dialog', { name: 'Confirmar fechamento', exact: true })
  await expect(dialog.getByLabel('Valor fechado (R$)')).toHaveValue('')
  await dialog.getByRole('button', { name: 'Cancelar', exact: true }).click()
  expect(leadWrites(state)).toHaveLength(0)
  await page.getByLabel('Etapa de Ana Ribeiro').selectOption({ label: 'Fechado' })
  await dialog.getByLabel('Valor fechado (R$)').fill('0')
  await dialog.getByRole('button', { name: 'Confirmar fechamento', exact: true }).click()
  await expect(dialog).toBeVisible(); expect(leadWrites(state)).toHaveLength(0)
  await dialog.getByLabel('Valor fechado (R$)').fill('37500')
  await dialog.getByRole('button', { name: 'Confirmar fechamento', exact: true }).click()
  await expect(dialog).not.toBeVisible()
  const saved = state.leads.find(row => row.data.name === 'Ana Ribeiro')!
  expect(saved.data).toMatchObject({ closedValue: 37500, status: 'Fechado' }); expect(saved.data.closedAt).toBeTruthy()
  expect(saved.stage_id).toBe(state.stages[workspaceA].find(row => row.type === 'WON')!.id)
  await navigateFeatures(page, 'Dashboard'); await expect(revenue(page)).toHaveText(/R\$\s*55\.500/)
  await page.reload(); await expect(revenue(page)).toHaveText(/R\$\s*55\.500/)
  expect(leadWrites(state)[0].body?.data).not.toHaveProperty('stageType'); clean(state)
})

test('LOST requires a loss reason and saves its optional comment separately from the objection', async ({ page }) => {
  const state = await mountFeatures(page)
  await navigateFeatures(page, 'Pipeline')
  await page.getByLabel('Etapa de Ana Ribeiro').selectOption({ label: 'Perdido' })
  const dialog = page.getByRole('dialog', { name: 'Por que esta oportunidade foi perdida?', exact: true })
  await dialog.getByRole('button', { name: 'Registrar perda', exact: true }).click()
  await expect(dialog).toBeVisible(); expect(leadWrites(state)).toHaveLength(0)
  await dialog.getByLabel('Motivo da perda').selectOption('Timing')
  await dialog.getByLabel('Comentário adicional').fill('Retomar no próximo trimestre após finalizar o contrato atual.')
  await dialog.getByRole('button', { name: 'Registrar perda', exact: true }).click()
  await expect(dialog).not.toBeVisible()
  expect(state.leads.find(row => row.data.name === 'Ana Ribeiro')?.data).toMatchObject({ status: 'Perdido', lossReason: 'Timing',
    lossComment: 'Retomar no próximo trimestre após finalizar o contrato atual.', objection: 'Caixa', closedValue: 0, closedAt: '' })
  await page.reload(); await navigateFeatures(page, 'Pipeline')
  await expect(page.getByLabel('Etapa de Ana Ribeiro').locator('option:checked')).toHaveText('Perdido'); clean(state)
})

test('nested LOST confirmation can be dismissed with Escape without losing the parent lead draft', async ({ page }) => {
  const state = await mountFeatures(page)
  await navigateFeatures(page, 'Pipeline')
  await page.locator('.lead-card').filter({ has: page.getByRole('heading', { name: 'Ana Ribeiro', exact: true }) }).getByRole('button', { name: /Ana Ribeiro/ }).click()
  const parent = page.getByRole('dialog', { name: 'Ana Ribeiro', exact: true })
  await parent.getByLabel('Observações').fill('Rascunho preservado ao cancelar a confirmação da perda.')
  await parent.getByLabel('Status').selectOption({ label: 'Perdido' })
  const child = page.getByRole('dialog', { name: 'Por que esta oportunidade foi perdida?', exact: true })
  await expect(child).toBeVisible(); await page.keyboard.press('Escape')
  await expect(child).not.toBeVisible(); await expect(parent).toBeVisible()
  await expect(parent.getByLabel('Status').locator('option:checked')).toHaveText('Compareceu')
  await expect(parent.getByLabel('Observações')).toHaveValue('Rascunho preservado ao cancelar a confirmação da perda.')
  expect(leadWrites(state)).toHaveLength(0)
  await parent.getByLabel('Status').selectOption({ label: 'Perdido' })
  await child.getByLabel('Motivo da perda').selectOption('Timing')
  await child.getByLabel('Comentário adicional').fill('Reavaliar após a contratação de um novo decisor.')
  await child.getByRole('button', { name: 'Registrar perda', exact: true }).click()
  await expect(child).not.toBeVisible(); await expect(parent).toBeVisible()
  await expect(parent.getByLabel('Motivo da perda')).toHaveValue('Timing')
  expect(leadWrites(state)).toHaveLength(0)
  await parent.getByRole('button', { name: 'Salvar alterações', exact: true }).click()
  await expect(parent).not.toBeVisible()
  expect(state.leads[0].data).toMatchObject({ lossReason: 'Timing', lossComment: 'Reavaliar após a contratação de um novo decisor.',
    notes: 'Rascunho preservado ao cancelar a confirmação da perda.' })
  expect(leadWrites(state)).toHaveLength(1); clean(state)
})

test('mobile landscape configuration can scroll to its Save action and persist changes', async ({ page }, info) => {
  await page.setViewportSize({ width: 667, height: 375 })
  const state = await mountFeatures(page, 'manager', { theme: 'dark' })
  const dialog = await openConfiguration(page)
  await dialog.getByLabel('Nome da etapa').first().fill('Contato inicial')
  const save = dialog.getByRole('button', { name: 'Salvar pipeline', exact: true })
  await save.scrollIntoViewIfNeeded()
  const bounds = await save.boundingBox()
  expect(bounds).not.toBeNull()
  expect(bounds!.y).toBeGreaterThanOrEqual(0)
  expect(bounds!.y + bounds!.height).toBeLessThanOrEqual(376)
  await expect(save).toBeVisible(); await noOverflow(page)
  await screenshot(page, info, 'landscape-save-reachable')
  await save.click(); await expect(dialog).not.toBeVisible()
  expect(state.stages[workspaceA][0].name).toBe('Contato inicial')
  expect(stageWrites(state)).toHaveLength(1)
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Visão geral.' })).toBeVisible()
  await expect(page.getByText('Salvo na nuvem', { exact: true })).toBeVisible()
  await navigateFeatures(page, 'Pipeline')
  await expect(page.getByRole('heading', { name: 'Contato inicial', exact: true })).toBeVisible(); clean(state)
})

test('invalid recording links cannot save; HTTPS opens safely and the complete seller post-call survives reload', async ({ page, context }) => {
  const state = await mountFeatures(page, 'closer'), dialog = await openCall(page)
  for (const invalid of ['javascript:alert(1)', 'http://recordings.example.invalid/call', 'https://user:password@recordings.example.invalid/call']) {
    await dialog.getByLabel('Link da gravação').fill(invalid)
    await dialog.getByRole('button', { name: 'Salvar revisão', exact: true }).click()
    await expect(dialog.getByRole('alert')).toContainText('HTTPS')
    expect(leadWrites(state)).toHaveLength(0)
  }
  const url = 'https://recordings.example.invalid/calls/ana'
  await dialog.getByLabel('Link da gravação').fill(url)
  await dialog.getByLabel('Próximo passo').fill('Confirmar a presença do sócio até quinta-feira.')
  await dialog.getByLabel('Resumo da conversa').fill('Lead com caixa disponível e dor operacional. Sócio participa da decisão.')
  await dialog.getByRole('group', { name: 'Nota da call de 0 a 10' }).getByRole('button', { name: '0', exact: true }).click()
  await dialog.getByRole('button', { name: 'Salvar revisão', exact: true }).click()
  await expect(dialog).not.toBeVisible()
  await page.reload(); const reopened = await openCall(page)
  await expect(reopened.getByLabel('Link da gravação')).toHaveValue(url)
  await expect(reopened.getByLabel('Próximo passo')).toHaveValue('Confirmar a presença do sócio até quinta-feira.')
  const link = reopened.getByRole('link', { name: 'Assistir gravação', exact: true }).first()
  await expect(link).toHaveAttribute('href', url); await expect(link).toHaveAttribute('target', '_blank')
  await expect(link).toHaveAttribute('rel', /noopener/); await expect(link).toHaveAttribute('rel', /noreferrer/)
  await context.route('https://recordings.example.invalid/**', route => route.fulfill({ contentType: 'text/html', body: '<title>Gravação fixture</title><p>Gravação simulada</p>' }))
  const popupPromise = page.waitForEvent('popup'); await link.click(); const popup = await popupPromise
  await expect(popup).toHaveURL(url); expect(await popup.evaluate(() => window.opener)).toBeNull(); await popup.close()
  expect(state.leads[0].data.callScore).toBe(0); expect(state.reviews[workspaceA]).toEqual([]); clean(state)
})

test('manager saves leadership feedback and a zero score independently of the seller assessment', async ({ page }) => {
  const fixture = createFeatureState(); fixture.leads[0].data.recordingUrl = 'https://recordings.example.invalid/calls/ana'
  const state = await mountFeatures(page, 'manager', { state: fixture }), seller = structuredClone(state.leads[0].data), dialog = await openCall(page)
  await expect(dialog.getByRole('link', { name: 'Assistir gravação', exact: true }).first()).toHaveAttribute('href', 'https://recordings.example.invalid/calls/ana')
  await dialog.getByLabel('Feedback da liderança').fill('Aprofunde o impacto antes de apresentar a proposta.')
  await dialog.getByLabel('Nota da liderança').fill('0')
  await dialog.getByRole('button', { name: 'Marcar como revisada', exact: true }).click()
  await expect(dialog.getByText('Revisada por Marcos Gestor', { exact: true })).toBeVisible()
  await expect(dialog.locator('.cf-leadership-score')).toHaveText('0/10')
  await expect(dialog.getByRole('status')).toContainText('Revisão da liderança salva.')
  expect(state.leads[0].data).toEqual(seller); expect(leadWrites(state)).toHaveLength(0)
  expect(reviewWrites(state)[0].body).toEqual({ p_workspace_id: workspaceA, p_lead_id: state.leads[0].id,
    p_feedback: 'Aprofunde o impacto antes de apresentar a proposta.', p_score: 0 })
  await page.reload(); const reopened = await openCall(page)
  await expect(reopened.getByLabel('Feedback da liderança')).toHaveValue('Aprofunde o impacto antes de apresentar a proposta.')
  await expect(reopened.getByLabel('Nota da liderança')).toHaveValue('0')
  await expect(reopened.getByRole('group', { name: 'Nota da call de 0 a 10' }).getByRole('button', { name: '8', exact: true })).toHaveAttribute('aria-pressed', 'true'); clean(state)
})

test('closer can read feedback but cannot alter leadership review; spoofed review in lead JSON is ignored', async ({ page }) => {
  const state = createFeatureState()
  state.leads[0].data.leadershipReview = { feedback: 'FORJADO NO JSON DO LEAD', score: 10, reviewedBy: memberIds.closer, reviewerName: 'Falso', reviewedAt: new Date().toISOString() }
  state.reviews[workspaceA].push({ lead_id: state.leads[0].id, feedback: 'Revisão oficial separada do pós-call', score: 7,
    reviewed_by: memberIds.manager, reviewer_name: 'Marcos Gestor', reviewed_at: new Date().toISOString() })
  await mountFeatures(page, 'closer', { state }); const dialog = await openCall(page)
  await expect(dialog.getByLabel('Feedback da liderança')).toHaveValue('Revisão oficial separada do pós-call')
  await expect(dialog.getByLabel('Feedback da liderança')).toHaveAttribute('readonly', '')
  await expect(dialog.getByRole('button', { name: 'Marcar como revisada', exact: true })).toHaveCount(0)
  await expect(dialog.getByLabel('Nota da liderança')).toHaveCount(0)
  await expect(page.getByText('FORJADO NO JSON DO LEAD')).toHaveCount(0)
  expect(reviewWrites(state)).toHaveLength(0); clean(state)
})

for (const role of ['closer', 'viewer'] as const) test(`${role} keeps seller post-call readonly when editing is not permitted`, async ({ page }) => {
  const state = createFeatureState(); state.leads[0].owner_id = memberIds.admin
  await mountFeatures(page, role, { state }); const dialog = await openCall(page)
  await expect(dialog.getByLabel('Resumo da conversa')).toBeDisabled()
  await expect(dialog.getByLabel('Link da gravação')).toBeDisabled()
  await expect(dialog.getByLabel('Próximo passo')).toBeDisabled()
  await expect(dialog.getByRole('button', { name: 'Salvar revisão', exact: true })).toHaveCount(0)
  await dialog.getByRole('button', { name: 'Fechar revisão' }).click()
  await expect(page.getByLabel('Comparecimento de Ana Ribeiro')).toBeDisabled()
  expect(leadWrites(state)).toHaveLength(0); expect(reviewWrites(state)).toHaveLength(0); clean(state)
})

test('pending and reviewed filters reflect official leadership reviews, independently of seller notes', async ({ page }) => {
  const state = createFeatureState()
  state.reviews[workspaceA].push({ lead_id: state.leads[0].id, feedback: 'Continue aprofundando a dor', score: 8,
    reviewed_by: memberIds.manager, reviewer_name: 'Marcos Gestor', reviewed_at: new Date().toISOString() })
  await mountFeatures(page, 'manager', { state }); await navigateFeatures(page, 'Calls')
  await expect(page.locator('.cp-calls-table tbody tr')).toHaveCount(3)
  await page.getByLabel('Revisão da liderança', { exact: true }).selectOption('pending')
  await expect(page.locator('.cp-calls-table tbody tr')).toHaveCount(2)
  await expect(page.getByRole('button', { name: 'Revisar call de Ana Ribeiro', exact: true })).toHaveCount(0)
  await page.getByLabel('Revisão da liderança', { exact: true }).selectOption('reviewed')
  await expect(page.locator('.cp-calls-table tbody tr')).toHaveCount(1)
  await expect(page.getByRole('button', { name: 'Revisar call de Ana Ribeiro', exact: true })).toBeVisible()
  await page.getByLabel('Buscar calls').fill('Bruno'); await expect(page.getByRole('heading', { name: 'Nenhuma call encontrada' })).toBeVisible()
  await page.getByRole('button', { name: 'Limpar busca e filtros' }).click()
  await expect(page.locator('.cp-calls-table tbody tr')).toHaveCount(3); clean(state)
})

test('a failed configuration save preserves the draft for retry and never changes stored stages early', async ({ page }) => {
  const state = await mountFeatures(page); state.failStageSave = true
  const dialog = await openConfiguration(page)
  await dialog.getByLabel('Nome da etapa').first().fill('Primeiro contato')
  await dialog.getByRole('button', { name: 'Salvar pipeline', exact: true }).click()
  await expect(dialog.getByRole('alert')).toContainText(/Não foi possível salvar/)
  await expect(dialog.getByLabel('Nome da etapa').first()).toHaveValue('Primeiro contato')
  expect(state.stages[workspaceA][0].name).toBe('Lead novo')
  state.failStageSave = false; await dialog.getByRole('button', { name: 'Salvar pipeline', exact: true }).click()
  await expect(dialog).not.toBeVisible(); expect(state.stages[workspaceA][0].name).toBe('Primeiro contato'); clean(state)
})

test('a failed leadership review preserves feedback, and an out-of-range score makes no request', async ({ page }) => {
  const state = await mountFeatures(page, 'manager'); state.failReviewSave = true
  const dialog = await openCall(page)
  await dialog.getByLabel('Feedback da liderança').fill('Ação prática para a próxima call')
  await dialog.getByLabel('Nota da liderança').fill('11')
  await dialog.getByRole('button', { name: 'Marcar como revisada', exact: true }).click()
  expect(reviewWrites(state)).toHaveLength(0)
  await dialog.getByLabel('Nota da liderança').fill('6')
  await dialog.getByRole('button', { name: 'Marcar como revisada', exact: true }).click()
  await expect(dialog.getByRole('alert')).toContainText(/Não foi possível salvar/)
  await expect(dialog.getByLabel('Feedback da liderança')).toHaveValue('Ação prática para a próxima call')
  expect(state.reviews[workspaceA]).toHaveLength(0)
  state.failReviewSave = false; await dialog.getByRole('button', { name: 'Marcar como revisada', exact: true }).click()
  await expect(dialog.getByText('Revisada por Marcos Gestor', { exact: true })).toBeVisible(); clean(state)
})

test('switching authorized companies refreshes distinct stages and reviews without retaining the previous company data', async ({ page }) => {
  const state = createFeatureState(); state.stages[workspaceB][4].name = 'Follow-up segunda empresa'
  await mountFeatures(page, 'admin', { state, twoWorkspaces: true }); await navigateFeatures(page, 'Pipeline')
  await expect(page.getByRole('heading', { name: 'SEGREDO SEGUNDA EMPRESA' })).toHaveCount(0)
  await page.getByLabel('Selecionar empresa').selectOption(workspaceB)
  await expect(page.getByText('Salvo na nuvem', { exact: true })).toBeVisible()
  await navigateFeatures(page, 'Pipeline')
  await expect(page.getByRole('heading', { name: 'SEGREDO SEGUNDA EMPRESA', exact: true })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Ana Ribeiro', exact: true })).toHaveCount(0)
  await expect(page.getByLabel('Etapa de SEGREDO SEGUNDA EMPRESA').locator('option:checked')).toHaveText('Follow-up segunda empresa')
  await page.getByLabel('Selecionar empresa').selectOption(workspaceA)
  await expect(page.getByText('Salvo na nuvem', { exact: true })).toBeVisible()
  await navigateFeatures(page, 'Pipeline')
  await expect(page.getByRole('heading', { name: 'Ana Ribeiro', exact: true })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Follow-up segunda empresa', exact: true })).toHaveCount(0)
  const stageReads = state.requests.filter(request => request.path.endsWith('/list_pipeline_stages'))
  expect(stageReads.map(request => request.body?.p_workspace_id)).toContain(workspaceB)
  expect(stageReads.at(-1)?.body?.p_workspace_id).toBe(workspaceA); clean(state)
})

for (const theme of ['light', 'dark'] as const) for (const viewport of [{ width: 1366, height: 900 }, { width: 390, height: 844 }]) {
  test(`${theme} ${viewport.width}px pipeline configuration and leadership call remain readable and fit the viewport`, async ({ page }, info) => {
    await page.setViewportSize(viewport)
    const state = await mountFeatures(page, 'admin', { theme })
    await expect(page.locator('.crm-visual')).toHaveAttribute('data-theme', theme)
    const dialog = await openConfiguration(page)
    await expect(dialog.getByLabel('Nome da etapa').first()).toBeVisible(); await noOverflow(page)
    await screenshot(page, info, 'pipeline-configuration')
    await dialog.getByRole('button', { name: 'Cancelar', exact: true }).click()
    const call = await openCall(page)
    await call.getByLabel('Feedback da liderança').fill('Conecte o impacto da dor ao próximo passo.')
    await call.getByLabel('Nota da liderança').fill('8')
    await call.getByRole('button', { name: 'Marcar como revisada', exact: true }).click()
    await expect(call.getByText('Revisada por Ana Administradora', { exact: true })).toBeVisible()
    await noOverflow(page); await screenshot(page, info, 'leadership-review')
    await call.getByRole('button', { name: 'Fechar revisão', exact: true }).click()
    await page.getByLabel('Tema da interface').selectOption(theme === 'dark' ? 'light' : 'dark')
    const reopened = await openCall(page)
    await expect(reopened.getByLabel('Feedback da liderança')).toHaveValue('Conecte o impacto da dor ao próximo passo.')
    await noOverflow(page); clean(state)
  })
}
