import { ArrowDownRight, ArrowRight, ArrowUpRight, CalendarDays, CircleDollarSign, MousePointer2, Target, TrendingUp, Video } from 'lucide-react'
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import type { Lead, Settings, PipelineStage } from '../types'
import { defaultPipelineStages, getLeadStageName, isWon, isLost } from '../lib/pipeline'
import { compactMoney, getMetrics, getMonthlyPerformance, initials, money, topObjections } from '../lib/analytics'

const palette = ['var(--color-chart-primary, #8b62d9)', 'var(--color-chart-secondary, #b59ae9)', 'var(--color-chart-neutral-1, #d8c9f1)', 'var(--color-chart-neutral-2, #ede6f8)', 'var(--color-chart-neutral-3, #a8b3c8)']
const stagePalette = ['var(--color-chart-neutral-1, #c6b9e6)', 'var(--color-chart-neutral-2, #ac95d4)', 'var(--color-chart-neutral-3, #9676ca)', 'var(--color-chart-secondary, #8660c0)', 'var(--color-chart-primary, #734caf)', 'var(--color-chart-success, #48a18b)']
const tooltipContentStyle = { backgroundColor: 'var(--color-surface-raised, #fff)', border: '1px solid var(--color-border, #ccc)', color: 'var(--color-text-primary, inherit)' }
const tooltipLabelStyle = { color: 'var(--color-text-primary, inherit)' }
const pct = (n: number) => `${n.toLocaleString('pt-BR', { maximumFractionDigits: 1 })}%`
export default function Dashboard({ leads, allLeads, previousLeads, settings, pipelineStages = defaultPipelineStages(), onPage, onEdit }: { leads: Lead[]; allLeads: Lead[]; previousLeads: Lead[]; settings: Settings; pipelineStages?: PipelineStage[]; onPage: (page: 'pipeline' | 'calls' | 'performance') => void; onEdit: (lead: Lead) => void }) {
  const metrics = getMetrics(leads)
  const previous = getMetrics(previousLeads)
  const months = getMonthlyPerformance(allLeads)
  const objections = topObjections(leads).slice(0, 5)
  const objectionTotal = objections.reduce((sum, item) => sum + item.count, 0)
  const goalPercent = settings.revenueGoal > 0 ? Math.min(metrics.revenue / settings.revenueGoal * 100, 100) : 0
  const upcoming = allLeads.filter(lead => lead.callDate && new Date(lead.callDate) >= new Date() && !isLost(lead) && !isWon(lead)).sort((a, b) => a.callDate.localeCompare(b.callDate)).slice(0, 4)
  const active = allLeads.filter(lead => !isLost(lead) && !isWon(lead))
  const stages = pipelineStages.filter(stage => stage.type !== 'LOST' && (stage.active || leads.some(lead => lead.stageId === stage.id))).map(stage => ({ id: stage.id, name: stage.name, count: leads.filter(lead => lead.stageId ? lead.stageId === stage.id : getLeadStageName(lead) === stage.name).length }))
  const stats = [
    { label: 'Faturamento', value: money(metrics.revenue), icon: CircleDollarSign, current: metrics.revenue, prior: previous.revenue, hint: `${metrics.closed} vendas fechadas`, tone: 'purple' },
    { label: 'Taxa de comparecimento', value: pct(metrics.showRate), icon: Video, current: metrics.showRate, prior: previous.showRate, hint: `${metrics.attended} calls realizadas`, tone: 'blue' },
    { label: 'Taxa de fechamento', value: pct(metrics.closeRate), icon: MousePointer2, current: metrics.closeRate, prior: previous.closeRate, hint: `${metrics.closed} de ${metrics.attended} calls`, tone: 'green' },
    { label: 'Ticket médio', value: money(metrics.averageTicket), icon: TrendingUp, current: metrics.averageTicket, prior: previous.averageTicket, hint: 'Por venda fechada', tone: 'orange' },
  ]
  return <>
    <div className="metrics-grid">{stats.map(({ label, value, icon: Icon, current, prior, hint, tone }) => {
      const change = prior > 0 ? (current - prior) / prior * 100 : null
      return <div className="stat-card" key={label}><div className="stat-top"><span className="stat-label">{label}</span><span className={`stat-icon ${tone}`}><Icon size={17} strokeWidth={1.8} /></span></div><div className="stat-value">{value}</div><div className="stat-bottom">{change !== null ? <span className={`trend ${change >= 0 ? 'positive' : 'negative'}`}>{change >= 0 ? <ArrowUpRight size={13} /> : <ArrowDownRight size={13} />}{Math.abs(change).toFixed(1).replace('.', ',')}%</span> : <span className="trend neutral">—</span>}<span>{hint}</span></div></div>
    })}</div>
    <div className="dashboard-chart-grid">
      <section className="panel revenue-panel"><div className="panel-header"><div><h2>Receita em movimento</h2><p>Seis meses da sua evolução em vendas</p></div><span className="chart-legend"><i />Faturamento</span></div><div className="chart-summary"><strong>{money(months.reduce((sum, month) => sum + month.revenue, 0))}</strong><span>acumulado nos últimos 6 meses</span></div><div className="revenue-chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={months} margin={{ top: 10, right: 5, left: -12, bottom: 0 }}><defs><linearGradient id="revenueGradient" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="var(--color-chart-primary, #8c60dc)" stopOpacity={0.24} /><stop offset="100%" stopColor="var(--color-chart-primary, #8c60dc)" stopOpacity={0.01} /></linearGradient></defs><CartesianGrid vertical={false} stroke="var(--color-chart-grid, #eef0f4)" strokeDasharray="4 4" /><XAxis dataKey="month" axisLine={false} tickLine={false} tick={{ fill: 'var(--color-chart-axis, #8991a0)', fontSize: 11 }} dy={9} /><YAxis width={72} tickFormatter={value => Number(value) === 0 ? 'R$ 0' : `${Number(value) / 1000} mil`} axisLine={false} tickLine={false} tick={{ fill: 'var(--color-chart-axis, #8991a0)', fontSize: 10 }} /><Tooltip formatter={value => [money(Number(value)), 'Faturamento']} contentStyle={{ ...tooltipContentStyle, border: '1px solid var(--color-border, #e9e5f2)', borderRadius: 12, fontSize: 12 }} labelStyle={tooltipLabelStyle} /><Area isAnimationActive={false} type="monotone" dataKey="revenue" stroke="var(--color-chart-primary, #8c60dc)" strokeWidth={2.8} fill="url(#revenueGradient)" activeDot={{ r: 5, strokeWidth: 4, stroke: 'var(--color-primary-soft, #e7ddfa)' }} /></AreaChart></ResponsiveContainer></div></section>
      <section className="panel goal-panel"><div className="panel-header"><div><h2>Sua meta, mais perto</h2><p>Faturamento no período selecionado</p></div><span className="stat-icon purple"><Target size={17} /></span></div><div className="goal-ring"><svg viewBox="0 0 180 180" aria-label={`${pct(goalPercent)} da meta alcançada`}><circle cx="90" cy="90" r="72" fill="none" stroke="var(--color-primary-soft, #f0ecf7)" strokeWidth="13" /><circle cx="90" cy="90" r="72" fill="none" stroke="var(--color-chart-primary, #9166dd)" strokeWidth="13" strokeLinecap="round" strokeDasharray={`${goalPercent / 100 * 452.39} 452.39`} transform="rotate(-90 90 90)" /></svg><div><strong>{Math.round(goalPercent)}<small>%</small></strong><span>da meta alcançada</span></div></div><div className="goal-values"><span><i className="dot purple-dot" />Realizado<strong>{compactMoney(metrics.revenue)}</strong></span><span><i className="dot gray-dot" />Meta<strong>{compactMoney(settings.revenueGoal)}</strong></span></div><div className="commission-row"><span>Comissão projetada <small>({settings.commissionRate}%)</small></span><strong>{money(metrics.revenue * settings.commissionRate / 100)}</strong></div></section>
    </div>
    <div className="dashboard-secondary-grid">
      <section className="panel pipeline-overview"><div className="panel-header"><div><h2>Seu pipeline em um olhar</h2><p>Cada conversa é uma nova oportunidade</p></div><button className="text-button" onClick={() => onPage('pipeline')}>Ver pipeline <ArrowRight size={14} /></button></div><div className="pipeline-stages" style={{ gridTemplateColumns: `repeat(${Math.max(stages.length, 1)}, minmax(80px, 1fr))`, overflowX: 'auto' }}>{stages.map((stage, index) => <div className="mini-stage" key={stage.id}><div className="mini-stage-label"><i style={{ background: stagePalette[index % stagePalette.length] }} />{stage.name}</div><strong>{stage.count.toString().padStart(2, '0')}</strong><div className="mini-stage-bar"><span style={{ width: `${Math.max(stage.count / Math.max(leads.length, 1) * 100, 8)}%`, background: stagePalette[index % stagePalette.length] }} /></div></div>)}</div><div className="pipeline-foot"><span><span className="live-dot" />{active.length} oportunidades em aberto</span><strong>{money(active.reduce((sum, lead) => sum + lead.ticket, 0))}<small> em potencial</small></strong></div></section>
      <section className="panel objections-panel"><div className="panel-header"><div><h2>O que trava suas vendas?</h2><p>Principais objeções dos leads</p></div></div>{objections.length ? <div className="objection-content"><div className="objection-donut"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie isAnimationActive={false} data={objections} dataKey="count" nameKey="name" innerRadius={45} outerRadius={63} paddingAngle={3} cornerRadius={3} stroke="none">{objections.map((item, index) => <Cell key={item.name} fill={palette[index]} />)}</Pie><Tooltip contentStyle={tooltipContentStyle} labelStyle={tooltipLabelStyle} /></PieChart></ResponsiveContainer><div className="donut-label"><strong>{objectionTotal}</strong><small>objeções</small></div></div><div className="objection-legend">{objections.map((item, index) => <div key={item.name}><i style={{ background: palette[index] }} /><span>{item.name}</span><strong>{Math.round(item.count / objectionTotal * 100)}%</strong></div>)}</div></div> : <div className="empty-state">As objeções registradas nas calls aparecerão aqui.</div>}</section>
    </div>
    <section className="panel upcoming-panel"><div className="panel-header"><div><h2>Próximas calls <span className="count-pill">{upcoming.length}</span></h2><p>Prepare a conversa. Construa o próximo sim.</p></div><button className="text-button" onClick={() => onPage('calls')}>Ver todas as calls <ArrowRight size={14} /></button></div><div className="table-scroll"><table className="data-table"><thead><tr><th>Lead / Empresa</th><th>Data e horário</th><th>Ticket previsto</th><th>Origem</th><th>Status</th><th aria-label="Ações" /></tr></thead><tbody>{upcoming.map(lead => <tr key={lead.id}><td><button className="lead-identity" onClick={() => onEdit(lead)}><span className="avatar" style={{ background: `var(--color-avatar-background, hsl(${lead.name.length * 27}, 35%, 93%))`, color: `var(--color-avatar-foreground, hsl(${lead.name.length * 27}, 30%, 42%))` }}>{initials(lead.name)}</span><span><strong>{lead.name}</strong><small>{lead.company || 'Sem empresa'}</small></span></button></td><td><span className="call-date"><CalendarDays size={14} />{new Date(lead.callDate).toLocaleDateString('pt-BR', { day: '2-digit', month: 'short' })}<small>{new Date(lead.callDate).toLocaleTimeString('pt-BR', { hour: '2-digit', minute: '2-digit' })}</small></span></td><td className="table-money">{money(lead.ticket)}</td><td><span className="source-label">{lead.source}</span></td><td><span className="badge scheduled"><i />{getLeadStageName(lead)}</span></td><td><button className="icon-button" aria-label={`Editar ${lead.name}`} onClick={() => onEdit(lead)}><ArrowUpRight size={17} /></button></td></tr>)}</tbody></table>{!upcoming.length && <div className="empty-state">Sua agenda está livre. Cadastre um lead e agende a próxima call.</div>}</div></section>
    <div className="dashboard-secondary-grid bottom-charts"><section className="panel"><div className="panel-header"><div><h2>Conversas que viram vendas</h2><p>Taxa de fechamento por mês</p></div><span className="stat-icon green"><TrendingUp size={16} /></span></div><div className="small-chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={months} margin={{ left: -20, right: 10, top: 10 }}><CartesianGrid vertical={false} stroke="var(--color-chart-grid, #eef0f4)" /><XAxis dataKey="month" tickLine={false} axisLine={false} tick={{ fontSize: 11, fill: 'var(--color-chart-axis, #8991a0)' }} /><YAxis unit="%" domain={[0, 100]} tickLine={false} axisLine={false} tick={{ fontSize: 10, fill: 'var(--color-chart-axis, #8991a0)' }} /><Tooltip formatter={value => [pct(Number(value)), 'Fechamento']} contentStyle={tooltipContentStyle} labelStyle={tooltipLabelStyle} /><Area isAnimationActive={false} type="monotone" dataKey="closeRate" stroke="var(--color-chart-success, #5d9e8c)" fill="var(--color-success-soft, #e9f4ef)" strokeWidth={2} /></AreaChart></ResponsiveContainer></div></section><section className="panel"><div className="panel-header"><div><h2>Qualificação que dá resultado</h2><p>Leads qualificados × vendas fechadas</p></div><div className="dual-legend"><span><i style={{ background: 'var(--color-chart-secondary, #ded3f2)' }} />Qualificados</span><span><i style={{ background: 'var(--color-chart-primary, #8d64d5)' }} />Fechados</span></div></div><div className="small-chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={months} margin={{ left: -25, right: 10, top: 10 }}><CartesianGrid vertical={false} stroke="var(--color-chart-grid, #eef0f4)" /><XAxis dataKey="month" tickLine={false} axisLine={false} tick={{ fontSize: 11, fill: 'var(--color-chart-axis, #8991a0)' }} /><YAxis allowDecimals={false} tickLine={false} axisLine={false} tick={{ fontSize: 10, fill: 'var(--color-chart-axis, #8991a0)' }} /><Tooltip contentStyle={tooltipContentStyle} labelStyle={tooltipLabelStyle} /><Bar isAnimationActive={false} name="Qualificados" dataKey="qualified" fill="var(--color-chart-secondary, #ded3f2)" radius={[4, 4, 0, 0]} maxBarSize={18} /><Bar isAnimationActive={false} name="Fechados" dataKey="closed" fill="var(--color-chart-primary, #8d64d5)" radius={[4, 4, 0, 0]} maxBarSize={18} /></BarChart></ResponsiveContainer></div></section></div>
  </>
}
