import { useState } from 'react'
import { Building2, Check, Trash2, UserRound, X } from 'lucide-react'
import { STATUSES, type Lead } from '../types'

const localDate = (value: string) => {
  if (!value) return ''
  const date = new Date(value)
  if (Number.isNaN(date.getTime())) return ''
  return new Date(date.getTime() - date.getTimezoneOffset() * 60000).toISOString().slice(0, 16)
}
export function makeLead(): Lead {
  return { id: crypto.randomUUID(), name: '', company: '', email: '', phone: '', ticket: 0, source: 'Instagram', createdAt: new Date().toISOString(), callDate: '', attendance: 'Pendente', objection: '', status: 'Lead novo', closedValue: 0, closedAt: '', lastContactAt: new Date().toISOString(), notes: '', pain: '', urgency: 'Média', financialCapacity: 'Não avaliada', decisionMaker: false, callScore: null, closerError: '', callSummary: '' }
}
export default function LeadForm({ lead, isNew, onSave, onClose, onDelete }: { lead: Lead; isNew: boolean; onSave: (lead: Lead) => void; onClose: () => void; onDelete: (id: string) => void }) {
  const [draft, setDraft] = useState(lead)
  const [confirmDelete, setConfirmDelete] = useState(false)
  const set = <K extends keyof Lead>(key: K, value: Lead[K]) => setDraft(current => ({ ...current, [key]: value }))
  const save = (event: React.FormEvent) => {
    event.preventDefault()
    onSave({ ...draft, name: draft.name.trim(), company: draft.company.trim(), attendance: draft.status === 'Fechado' ? 'Compareceu' : draft.attendance, closedAt: draft.status === 'Fechado' ? draft.closedAt || new Date().toISOString() : '', closedValue: draft.status === 'Fechado' ? draft.closedValue : 0 })
  }
  return <div className="modal-backdrop" onMouseDown={event => { if (event.target === event.currentTarget) onClose() }}><section className="lead-drawer" role="dialog" aria-modal="true" aria-labelledby="lead-dialog-title"><header className="drawer-header"><div className="drawer-heading-icon"><UserRound size={21} /></div><div><h2 id="lead-dialog-title">{isNew ? 'Uma nova oportunidade' : draft.name}</h2><p>{isNew ? 'Boas vendas começam com boas conversas.' : 'Cada detalhe ajuda a construir o próximo sim.'}</p></div><button type="button" className="icon-button" aria-label="Fechar formulário" onClick={onClose}><X size={21} /></button></header><form onSubmit={save} className="lead-form"><div className="form-scroll"><div className="form-section-title"><UserRound size={15} />Sobre o lead</div><div className="form-grid"><label className="full-field">Nome do lead <span>*</span><input required autoFocus maxLength={100} value={draft.name} onChange={event => set('name', event.target.value)} placeholder="Ex.: Mariana Costa" /></label><label className="full-field">Empresa<input maxLength={120} value={draft.company} onChange={event => set('company', event.target.value)} placeholder="Nome da empresa" /></label><label>E-mail<input type="email" value={draft.email} onChange={event => set('email', event.target.value)} placeholder="nome@empresa.com" /></label><label>WhatsApp<input type="tel" value={draft.phone} onChange={event => set('phone', event.target.value)} placeholder="(11) 99999-9999" /></label><label>Origem<select value={draft.source} onChange={event => set('source', event.target.value)}>{['Instagram', 'Indicação', 'Tráfego pago', 'LinkedIn', 'Outbound', 'Orgânico', 'Evento', 'Outro', ...(!['Instagram', 'Indicação', 'Tráfego pago', 'LinkedIn', 'Outbound', 'Orgânico', 'Evento', 'Outro'].includes(draft.source) ? [draft.source] : [])].map(source => <option key={source}>{source}</option>)}</select></label><label>Ticket previsto (R$)<input type="number" min="0" step="0.01" value={draft.ticket || ''} onChange={event => set('ticket', Number(event.target.value))} placeholder="15.000" /></label></div><div className="form-section-title"><Building2 size={15} />Oportunidade e call</div><div className="form-grid"><label>Status<select value={draft.status} onChange={event => {
      const status = event.target.value as Lead['status']
      setDraft(current => ({ ...current, status, ...(status === 'Fechado' ? { closedValue: current.closedValue || current.ticket, attendance: 'Compareceu' as const } : {}) }))
    }}>{STATUSES.map(status => <option key={status}>{status}</option>)}</select></label><label>Comparecimento<select value={draft.attendance} onChange={event => set('attendance', event.target.value as Lead['attendance'])} disabled={draft.status === 'Fechado'}><option>Pendente</option><option>Compareceu</option><option>Não compareceu</option></select></label><label className="full-field">Data da call<input type="datetime-local" value={localDate(draft.callDate)} onChange={event => set('callDate', event.target.value ? new Date(event.target.value).toISOString() : '')} /></label><label className="full-field">Último contato<input type="datetime-local" required value={localDate(draft.lastContactAt)} onChange={event => set('lastContactAt', event.target.value ? new Date(event.target.value).toISOString() : '')} /><small>Após 5 dias sem contato, o lead aparece em vermelho.</small></label>{draft.status === 'Fechado' && <><label>Valor fechado (R$) <span>*</span><input required type="number" min="0.01" step="0.01" value={draft.closedValue || ''} onChange={event => set('closedValue', Number(event.target.value))} /></label><label>Data de fechamento<input type="datetime-local" value={localDate(draft.closedAt)} onChange={event => set('closedAt', event.target.value ? new Date(event.target.value).toISOString() : '')} /></label></>}<label className="full-field">Objeção principal<input list="objections" maxLength={100} value={draft.objection} onChange={event => set('objection', event.target.value)} placeholder="Qual é a principal barreira para o sim?" /><datalist id="objections"><option value="Preço" /><option value="Momento" /><option value="Decisor" /><option value="Confiança" /><option value="Caixa" /></datalist></label><label className="full-field">Observações<textarea rows={4} value={draft.notes} onChange={event => set('notes', event.target.value)} placeholder="Contexto, próximos passos e o que vale lembrar…" /></label></div></div><footer className="drawer-footer">{!isNew && <button type="button" className="icon-button danger" aria-label="Excluir lead" onClick={() => setConfirmDelete(true)}><Trash2 size={18} /></button>}<button type="button" className="button button-secondary" onClick={onClose}>Cancelar</button><button type="submit" className="button button-primary"><Check size={16} />{isNew ? 'Cadastrar lead' : 'Salvar alterações'}</button></footer></form>{confirmDelete && <div className="drawer-confirm"><div><Trash2 size={28} /><h3>Excluir este lead?</h3><p>Os dados desta oportunidade serão removidos, incluindo a avaliação da call.</p><button className="button button-danger" onClick={() => onDelete(draft.id)}>Excluir lead</button><button className="button button-secondary" onClick={() => setConfirmDelete(false)}>Manter lead</button></div></div>}</section></div>
}
