import { useState } from 'react'
import { AlertCircle, ArrowUpRight, CalendarDays, Columns3, LayoutList, Plus, Search, SlidersHorizontal } from 'lucide-react'
import { STATUSES, type Lead, type LeadStatus } from '../types'
import { initials, isStale, money } from '../lib/analytics'

const colors = ['#afa3ce', '#9581c4', '#7194d6', '#d3a064', '#b67fc3', '#4e9e80', '#bf818a']
export default function Pipeline({ leads, onEdit, onAdd, onUpdate }: { leads: Lead[]; onEdit: (lead: Lead) => void; onAdd: (status?: LeadStatus) => void; onUpdate: (lead: Lead) => void }) {
  const [search, setSearch] = useState('')
  const [view, setView] = useState<'board' | 'list'>('board')
  const [source, setSource] = useState('Todas as origens')
  const [onlyStale, setOnlyStale] = useState(false)
  const [dragging, setDragging] = useState<string | null>(null)
  const filtered = leads.filter(lead => `${lead.name} ${lead.company}`.toLowerCase().includes(search.toLowerCase()) && (source === 'Todas as origens' || source === lead.source) && (!onlyStale || isStale(lead)))
  const move = (id: string, status: LeadStatus) => {
    const lead = leads.find(item => item.id === id)
    if (!lead || lead.status === status) return
    if (status === 'Fechado') { onEdit({ ...lead, status, closedValue: lead.closedValue || lead.ticket }); return }
    onUpdate({ ...lead, status, closedValue: 0, closedAt: '', ...(status === 'Compareceu' ? { attendance: 'Compareceu' as const } : {}) })
  }
  return <><div className="pipeline-toolbar"><div className="filter-search"><Search size={16} /><input value={search} onChange={event => setSearch(event.target.value)} placeholder="Buscar por lead ou empresa" aria-label="Buscar no pipeline" /></div><div className="pipeline-filters"><label className="select-wrap"><SlidersHorizontal size={14} /><select aria-label="Filtrar por origem" value={source} onChange={event => setSource(event.target.value)}><option>Todas as origens</option>{Array.from(new Set(leads.map(lead => lead.source))).map(item => <option key={item}>{item}</option>)}</select></label><button className={`button ${onlyStale ? 'button-danger-light' : 'button-secondary'}`} onClick={() => setOnlyStale(!onlyStale)}><AlertCircle size={15} />Sem resposta<span className="count-pill">{leads.filter(lead => isStale(lead)).length}</span></button><div className="view-switch"><button aria-label="Visualização em colunas" className={view === 'board' ? 'active' : ''} onClick={() => setView('board')}><Columns3 size={17} /></button><button aria-label="Visualização em lista" className={view === 'list' ? 'active' : ''} onClick={() => setView('list')}><LayoutList size={17} /></button></div></div></div><div className="pipeline-summary"><strong>{filtered.length}</strong> oportunidades <span>•</span> <strong>{money(filtered.filter(lead => lead.status !== 'Perdido').reduce((sum, lead) => sum + (lead.status === 'Fechado' ? lead.closedValue : lead.ticket), 0))}</strong> em negócios <small>Arraste os cards para atualizar a etapa</small></div>{view === 'board' ? <div className="kanban-board">{STATUSES.map((status, index) => {
    const items = filtered.filter(lead => lead.status === status)
    return <section key={status} className={`kanban-column ${dragging ? 'drop-enabled' : ''}`} onDragOver={event => event.preventDefault()} onDrop={event => { event.preventDefault(); move(event.dataTransfer.getData('text/plain'), status); setDragging(null) }}><div className="kanban-column-header"><i style={{ background: colors[index] }} /><h2>{status}</h2><span>{items.length}</span><button aria-label={`Adicionar lead em ${status}`} onClick={() => onAdd(status)}><Plus size={15} /></button></div><p className="kanban-column-total">{money(items.reduce((sum, lead) => sum + (status === 'Fechado' ? lead.closedValue : lead.ticket), 0))}</p><div className="kanban-cards">{items.map(lead => <article className={`lead-card ${isStale(lead) ? 'stale' : ''} ${dragging === lead.id ? 'dragging' : ''}`} key={lead.id} draggable onDragStart={event => { event.dataTransfer.setData('text/plain', lead.id); setDragging(lead.id) }} onDragEnd={() => setDragging(null)}><button className="lead-card-main" onClick={() => onEdit(lead)}><span className="lead-card-heading"><span className="avatar small">{initials(lead.name)}</span><ArrowUpRight size={15} /></span><h3>{lead.name}</h3><p>{lead.company || 'Pessoa física'}</p><strong>{money(lead.status === 'Fechado' ? lead.closedValue : lead.ticket)}</strong><span className="lead-card-source">{lead.source}</span>{lead.callDate && <span className="lead-card-date"><CalendarDays size={12} />{new Date(lead.callDate).toLocaleDateString('pt-BR', { day: '2-digit', month: 'short' })}</span>}{isStale(lead) && <span className="stale-note"><AlertCircle size={12} />Há mais de 5 dias sem contato</span>}</button><label className="card-status-label">Mover para<select aria-label={`Etapa de ${lead.name}`} value={lead.status} onChange={event => move(lead.id, event.target.value as LeadStatus)}>{STATUSES.map(item => <option key={item}>{item}</option>)}</select></label></article>)}{!items.length && <div className="kanban-empty">Nenhuma oportunidade nesta etapa</div>}</div></section>
  })}</div> : <div className="panel table-scroll"><table className="data-table"><thead><tr><th>Lead / Empresa</th><th>Ticket</th><th>Origem</th><th>Etapa</th><th>Último contato</th><th /></tr></thead><tbody>{filtered.map(lead => <tr key={lead.id} className={isStale(lead) ? 'stale-row' : ''}><td><button className="lead-identity" onClick={() => onEdit(lead)}><span className="avatar">{initials(lead.name)}</span><span><strong>{lead.name}</strong><small>{lead.company}</small></span></button></td><td className="table-money">{money(lead.status === 'Fechado' ? lead.closedValue : lead.ticket)}</td><td>{lead.source}</td><td><select aria-label={`Etapa de ${lead.name}`} value={lead.status} onChange={event => move(lead.id, event.target.value as LeadStatus)}>{STATUSES.map(item => <option key={item}>{item}</option>)}</select></td><td>{new Date(lead.lastContactAt).toLocaleDateString('pt-BR')}{isStale(lead) && <span className="stale-note">Follow-up pendente</span>}</td><td><button className="icon-button" aria-label={`Editar ${lead.name}`} onClick={() => onEdit(lead)}><ArrowUpRight size={17} /></button></td></tr>)}</tbody></table>{!filtered.length && <div className="empty-state">Nenhum lead encontrado. Experimente ajustar os filtros.</div>}</div>}</>
}
